Killer_app/Killer_app/Controllers/LogInController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Killer_app.Model;

namespace Killer_app.Controllers
{
    public class LogInController : Controller
    {
        private MainController controller = new MainController();
        // GET: LogIn
        public ActionResult Index()
        {
            return View();
        }
        //POST : LogIn
        [HttpPost]
        public ActionResult Index(FormCollection collection)
        {
            if(!ModelState.IsValid)
            {
                return View();
            }
            string mystring = collection["Naam"];
            string otherstring = collection["Wachtwoord"];
            Model.User user = controller.GetUser(collection["Naam"]);
            if (user != null && user.Wachtwoord == collection["Wachtwoord"])
            {
                Session["user"] = user;
                return RedirectToAction("Index", "Shop");
            }
            return View();
        }
        public ActionResult LogOff()
        {
            Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public ActionResult Register()
        {
            return View();
        }
    }
}

Killer_app/Killer_app/Views/LogIn/Index.cshtml

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>LogIn</h2>
@using (Html.BeginForm("Index", "LogIn"))
{
    <div>@Html.Label("UserName")</div>
    <input type="text" name="Naam" class="form-control" />
    <div>@Html.Label("Wachtwoord")</div>
    <input type="text" name="Wachtwoord" class="form-control" />
    <button type="submit">Log in</button>
}


Killer_app/Killer_app/Views/LogIn/Register.cshtml

@{
    ViewBag.Title = "Register";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Register</h2>
