Killer_app/Killer_app/Controllers/AdminGameController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Killer_app.Model;
using Killer_app.Logic;
using Killer_app.Data;
using PagedList;

namespace Killer_app.Controllers
{
    public class AdminGameController : Controller
    {
        private MainController controller = new MainController();
        // GET: Shop
        public ActionResult Index(int? page)
        {
            List<Game> games = controller.GetAllGames();


            int pageNumber = (page ?? 1);
            return View(games.ToPagedList(pageNumber, 6));
        }
        //GET: Delete/id
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Game game = controller.GetGame((int)id);
            return View(game);
        }
        //POST: Delete/id
        [HttpPost]
        public ActionResult Delete(int id)
        {
            if (controller.DeleteGame(id))
            {
                return RedirectToAction("Index");
            }
            else{ return View(controller.GetGame(id)); }
        }
        //GET: Edit/id
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }
            Game game = controller.GetGame((int)id);
            return View(game);
        }
        //POST: Edit/id
        [HttpPost]
        public ActionResult Edit(FormCollection collection)
        {
            Game game = controller.GetGame(Convert.ToInt32(collection["ID"]));
            byte[] picture = null;
            HttpPostedFileBase file = Request.Files["file"];
            if (file.ContentLength != 0)
            {
                using (System.IO.MemoryStream ms = new System.IO.MemoryStream())
                {
                    file.InputStream.CopyTo(ms);
                    picture = ms.GetBuffer();
                }
            }
            else { picture = game.Image; }
            try
            {
                if (game.EditGame(collection["Naam"], Convert.ToDecimal(collection["Prijs"]), collection["Trailer"], Convert.ToDecimal(collection["Score"]), picture, Convert.ToDecimal(collection["OudePrijs"])))
                {
                    return RedirectToAction("Index");
                }
                else{ return View(game); }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
                return View();
            }
        }
        //GET: Create
        public ActionResult Create()
        {
            return View();
        }
        //POST : Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            //Gets the file and converts into a byte array
            HttpPostedFileBase file = Request.Files["file"];
            byte[] picture = null;
            using (System.IO.MemoryStream ms = new System.IO.MemoryStream())
            {
                file.InputStream.CopyTo(ms);
                picture = ms.GetBuffer();
            }
            //Inserts data from formcollection and from image
            if (controller.InsertGame(new Game(collection["Naam"], Convert.ToDecimal(collection["Prijs"]), collection["Trailer"], Convert.ToDecimal(collection["Score"]), picture)))
            {
                return RedirectToAction("Index");
            }
            else{ return View(); }
        }

    }
}

Killer_app/Killer_app/Views/AdminGame/Create.cshtml

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Create Game</h2>


@using (Html.BeginForm("Create", "AdminGame", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>@Html.Label("Naam")</div>
    <input type="text" name="Naam" class="form-control" /><br />
    <div>@Html.Label("Prijs")</div>
    <input type="text" name="Prijs" class="form-control" /><br />
    <div>@Html.Label("Score")</div>
    <input type="text" name="Score" class="form-control" /><br />
    <div>@Html.Label("Trailer")</div>
    <input type="text" name="Trailer" class="form-control" /><br />
    <div>@Html.Label("Foto")</div>
    <input type="file" name="file" id="file" style="width: 100%;" />
    <br />
    <br />
    <button class="btn-lg" type="submit">Create</button>
}




Killer_app/Killer_app/Views/AdminGame/Delete.cshtml
@model Killer_app.Model.Game
<form method="post">
    <h2>Are you sure you want to delete @Model.Naam?</h2>
    <button type="submit">Delete</button>
</form>


Killer_app/Killer_app/Views/AdminGame/Edit.cshtml
@model Killer_app.Model.Game

@{

}

<h2>Edit</h2>
@using (Html.BeginForm("Edit", "AdminGame", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div>@Html.Label("ID")</div>
    <input name="ID" class="form-control" value=" @Model.ID" readonly /><br />
    <div>@Html.Label("Naam")</div>   
    <input type="text" name="Naam" class="form-control" value="@Model.Naam"/><br />
    <div>@Html.Label("Prijs")</div>
    <input type="text" name="Prijs" class="form-control" value="@Model.Prijs" /><br />
    <div>@Html.Label("OudePrijs")</div>
    <input type="text" name="OudePrijs" class="form-control" value="@Model.OudePrijs" /><br />
    <div>@Html.Label("Score")</div>
    <input type="text" name="Score" class="form-control" value="@Model.Score"/><br />
    <div>@Html.Label("Trailer")</div>
    <input type="text" name="Trailer" class="form-control" value="@Model.Trailer" /><br />
    <div>@Html.Label("Foto")</div>
    <input type="file" name="file" /><br />
    <button type="submit">Save</button>
}



Killer_app/Killer_app/Views/AdminGame/Index.cshtml
@model PagedList.IPagedList<Killer_app.Model.Game>
@using PagedList.Mvc;
<link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Games</h2>
@Html.ActionLink("Create", "Create")
<table class="table">
    <tr>
        <th>ID</th>
        <th>Naam</th>
        <th>Prijs</th>
        <th>OudePrijs</th>
        <th>Score</th>
        <th>TrailerLink</th>
        <th>ImageLink</th>
        <th>Actions</th>
    </tr>
    @foreach (var game in Model)
    {
        <tr>

            <td>
                @game.ID
            </td>
            <td>
                @game.Naam
            </td>
            <td>
                @game.Prijs
            </td>
            <td>
                @game.OudePrijs
            </td>
            <td>
                @game.Score
            </td>
            <td>
                @game.Trailer
            </td>
            <td>
                @game.Image
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = game.ID })
                @Html.ActionLink("Delete", "Delete", new { id = game.ID })
            </td>
        </tr>
    }
</table>
<br />
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, page => Url.Action("Index",
    new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
